language: python
sudo: false
python:
  - 2.7
addons:
  apt:
    packages:
      - cmake
      - build-essential
      - ninja-build
install:
  - pip install -U yotta
script:
  - yt build
notifications:
  email:
    on_success: change
    on_failure: change
