language: python
sudo: false
python:
  - 2.7
addons:
  apt:
    packages:
      - cmake
      - build-essential
      - ninja-build
      - libssl-dev
install:
  - pip install yotta
script:
  - yt build
